name: Build docker image
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
    - 'app/**'
  pull_request:
    branches:
      - 'master'
    paths:
    - 'app/**'

jobs:
# Build and Push image
  build:
    name: Build and Push image
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_id.outputs.id }}
    steps:
    - name: Generate build id
      id: build_id
      # add a step output `steps.build_id.outputs.id` as the unique id
      run: echo "::set-output name=id::$(date +%Y%m%d-%H%M%S)"

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: zppfan/http-server
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    -   name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (buildx)
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: app/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
